export const steps = [
	{
		id: "level",
		title: "Select Learning Level",
		content: "What’s your learning level?",
		options: [
			{ id: "beginner", label: "Beginner" },
			{ id: "intermediate", label: "Intermediate" },
			{ id: "advanced", label: "Advanced" },
		],
	},
	{
		id: "course",
		title: "Select Course",
		content: "Which course are you starting with?",
		options: [
			{ id: "jamb", label: "JAMB" },
			{ id: "waec", label: "WAEC" },
			{ id: "ielts", label: "IELTS" },
			{ id: "toefl", label: "TOEFL" },
		],
	},
	{
		id: "subject",
		title: "Select Subject",
		content: "Which subject are you working on first?",
		options: [
			{ id: "chemistry", label: "Chemistry" },
			{ id: "physics", label: "Physics" },
			{ id: "government", label: "Government" },
			{ id: "literature", label: "Literature" },
			{ id: "english", label: "English" },
			{ id: "mathematics", label: "Mathematics" },
			{ id: "further-math", label: "Further Mathematics" },
			{ id: "economics", label: "Economics" },
			{ id: "geography", label: "Geography" },
			{ id: "biology", label: "Biology" },
			{ id: "commerce", label: "Commerce" },
			{ id: "reading", label: "Reading" },
			{ id: "writing", label: "Writing" },
			{ id: "listening", label: "Listening" },
			{ id: "speaking", label: "Speaking" },
		],
	},
	{
		id: "confident",
		title: "Select One Option",
		content: "How confident are you in this subject?",
		options: [
			{ id: "struggling", label: "I’m struggling" },
			{ id: "okay_sometimes", label: "I’m okay, but need help sometimes" },
			{ id: "quick_answers", label: "I just need quick answers" },
			{ id: "master", label: "I want to master it" },
		],
	},
	{
		id: "topic",
		title: "Select a topic",
		content: "Alright, let’s select a topic to begin with",
		options: [
			{ id: "comprehension", label: "Comprehension" },
			{ id: "grammar", label: "Grammar" },
			{ id: "essay", label: "Essay Writing" },
			{ id: "lexis", label: "Lexis and Structure" },

			{ id: "algebra", label: "Algebra" },
			{ id: "geometry", label: "Geometry" },
			{ id: "trigonometry", label: "Trigonometry" },
			{ id: "statistics", label: "Statistics" },

			{ id: "cells", label: "Cells & Cell Structure" },
			{ id: "genetics", label: "Genetics" },
			{ id: "ecology", label: "Ecology" },
			{ id: "reproduction", label: "Reproduction" },

			{ id: "atomic", label: "Atomic Structure" },
			{ id: "periodic", label: "Periodic Table" },
			{ id: "bonding", label: "Chemical Bonding" },
			{ id: "reactions", label: "Chemical Reactions" },

			{ id: "motion", label: "Motion" },
			{ id: "waves", label: "Waves" },
			{ id: "electricity", label: "Electricity" },
			{ id: "energy", label: "Energy & Power" },
			{ id: "constitution", label: "Constitution" },
			{ id: "arms", label: "Arms of Government" },
			{ id: "elections", label: "Elections & Voting" },

			{ id: "poetry", label: "Poetry" },
			{ id: "prose", label: "Prose" },
			{ id: "drama", label: "Drama" },
		],
	},
	{
		id: "ready",
		title: "Select an Option",
		content: "Are you ready to start learning?",
		options: [{ id: "yes", label: "I’m ready" }],
	},
];
