version: "3"

services:
 app:
  container_name: classore
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - ./:/app
   - /app/node_modules
   - /app/.next
  ports:
   - "3010:3010"
  env_file:
   - .env
  restart: unless-stopped
