export { default as arrow } from "./arrow.png"
export { default as learn } from "./learn.png"
export * from "./modal-art"
export { default as onlineLearning } from "./online-learning.png"
export { default as solutionIllustration } from "./solution-illustration.png"
export { default as squiggly } from "./squiggly.png"
export { default as testingIllustration } from "./testing-illustration.png"
